engines:
  rubocop:
    enabled: true
    exclude_fingerprints:
    - d5f030d9e184225629412adeca50f2c2
    checks:
      Rubocop/Lint/AssignmentInCondition:
        enabled: false
      Rubocop/Rails/HasAndBelongsToMany:
        enabled: false
  golint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
exclude_paths:
- spec/**/*
- vendor/**/*
- db/**/*
- config/**/*
- bin/**/*
- "Gemfile"
- "Rakefile"
- "app/controllers/trails_controller/look_up.rb"
