engines:
  rubocop:
    enabled: true
    checks:
      Rubocop/Lint/AssignmentInCondition:
        enabled: false
  golint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
exclude_paths:
- spec/**/*
- vendor/**/*
- db/**/*
- config/**/*
- "Gemfile"
- "Rakefile"
- "app/controllers/trails_controller/look_up.rb"
