language: ruby
rvm:
  - 2.2.3

before_install:
  - rvm @global do gem uninstall bundler -a -x
  - rvm @global do gem install bundler -v 1.10.6
env:
  - TEST_SUITE=features
  - TEST_SUITE=controllers
  - TEST_SUITE=models
before_script:
  ## Required to run browser tests (FF) ##
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - bundle exec rspec spec/$TEST_SUITE/*
