language: ruby
rvm:
  - 2.2.3

before_install:
  - rvm @global do gem uninstall bundler -a -x
  - rvm @global do gem install bundler -v 1.10.6
env:
  - TEST_SUITE=features
  - TEST_SUITE=controllers
  - TEST_SUITE=models
script:
  - bundle exec rspec spec/$TEST_SUITE/*

addons:
  sauce_connect:
    username: "carlosgabaldon"
    access_key: "e11459bc-68d0-40a6-a5f7-c4452b97e0de"
