language: ruby
rvm:
  - 2.2.3
bundler_args: --without development production --quiet
env:
  - TEST_SUITE=features
  - TEST_SUITE=controllers
  - TEST_SUITE=models
script:
  - bundle exec rspec spec/$TEST_SUITE/*
